# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of Ardea's CarriageService, the travel carriage the arm rides on. Its two
# properties answer; its one command does not.
#
# `StationNames` is the station map's names (`Base1`, `Base2`, ... -- see
# `mock_instruments.stations`), which is exactly the set `LabwareService.Transfer` accepts. On the
# machine the same list comes from the motion configuration, and it is likewise fixed for the
# server's lifetime.
#
# `CarriagePosition` is a synthetic position -- the station's index in that list times a fixed
# pitch (`mock_instruments.ardea`, `Ardea.station_position_mm`). The transporter publishes it as
# the carriage reaches each end of a transfer's route, so the property behaves like the real one
# in the way that matters to a client: it is stable while nothing moves and it changes when
# something does. It is not the machine's geometry, and a client should not read distance into it.
#
# `MoveCarriage` refuses. Positioning the carriage on its own has no counterpart in a world
# model that records where labware *is* rather than where the machine is pointed, and the
# transfer that does need the carriage moves it itself.
from __future__ import annotations

import logging
from queue import Queue
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from ..generated.carriageservice import (
    CarriageServiceBase,
    MoveCarriage_IntermediateResponses,
    MoveCarriage_Responses,
)
from .unimplemented import unimplemented

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)

_FEATURE = "CarriageService"


class CarriageServiceImpl(CarriageServiceBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._instrument = parent_server.instrument

        # Publish every carriage position the transporter reports. Subscribing also publishes
        # its starting position (0.0, "wherever it was left" -- see `mock_instruments.ardea`),
        # so the observable property has a value from the moment the server is up.
        self._instrument.carriage_position.subscribe(self.update_CarriagePosition)

    def CarriagePosition_on_subscription(self, *, metadata: MetadataDict) -> Queue[float] | None:
        # Emit the current position immediately to a new subscriber, rather than leaving it
        # waiting for the next transfer to publish one.
        queue = super().CarriagePosition_on_subscription(metadata=metadata)
        try:
            self.update_CarriagePosition(self.current_CarriagePosition, queue=queue)
        except AttributeError:
            self.update_CarriagePosition(0.0, queue=queue)
        return queue

    def get_StationNames(self, *, metadata: MetadataDict) -> list[str]:
        return self._instrument.station_names()

    def MoveCarriage(
        self,
        StationId: str,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[MoveCarriage_IntermediateResponses],
    ) -> MoveCarriage_Responses:
        unimplemented(_FEATURE, "MoveCarriage")
