# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of ConnectionService. Its one command refuses.
#
# The second `kvcomplus-sila2` provider feature (see `deviceservice_impl.py`). `GetMode`
# reports the operating mode of the KV COM+ connection to the PLC.
#
# It refuses rather than reporting a healthy connection, because a mock that always says the
# link is up teaches a client to trust an answer that costs nothing here and can be false on
# the bench. There is no PLC link in this lab: what stands in for "the machine is reachable"
# is that the SiLA2 server answers at all.
from __future__ import annotations

import logging

from sila2.server import MetadataDict

from ..generated.connectionservice import ConnectionServiceBase, GetMode_Responses
from .unimplemented import unimplemented

logger = logging.getLogger(__name__)

_FEATURE = "ConnectionService"


class ConnectionServiceImpl(ConnectionServiceBase):
    def GetMode(self, *, metadata: MetadataDict) -> GetMode_Responses:
        unimplemented(_FEATURE, "GetMode")
