# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of DeviceService. Both commands refuse.
#
# This feature belongs to `kvcomplus-sila2`, the KEYENCE PLC provider the real Ardea server
# vendors and exposes alongside its own features. It reads and writes PLC devices by number
# (`D6002`, `D5050`, ...) -- the raw signal layer underneath Ardea's carriage and hand
# commands.
#
# It refuses because a PLC address space has no counterpart in a world model, and because the
# addresses are the machine's wiring: on the real bench a write to the wrong device number
# moves something. The one PLC-backed reading a client here might actually want -- the machine
# light -- is served as `LabwareService.LightIsOn` out of the world model's device state
# instead, which is a name that means the same thing on both sides.
from __future__ import annotations

import logging

from sila2.server import MetadataDict

from ..generated.deviceservice import DeviceServiceBase, ReadDevice_Responses, WriteDevice_Responses
from .unimplemented import unimplemented

logger = logging.getLogger(__name__)

_FEATURE = "DeviceService"


class DeviceServiceImpl(DeviceServiceBase):
    def ReadDevice(self, DeviceType: int, DeviceNumber: str, *, metadata: MetadataDict) -> ReadDevice_Responses:
        unimplemented(_FEATURE, "ReadDevice")

    def WriteDevice(
        self, DeviceType: int, DeviceNumber: str, Value: int, *, metadata: MetadataDict
    ) -> WriteDevice_Responses:
        unimplemented(_FEATURE, "WriteDevice")
