# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written SiLA2 adapter for Ardea's LabwareService. The one command the mock performs,
# `Transfer`, is `mock_instruments.ardea.Ardea.transfer` -- station resolution, the two
# world-model moves through the arm, the seven phases and their timing all live there. This
# class maps it onto SiLA2:
#
#   * `instance.begin_execution` becomes the instrument's `execution.begin`, and each phase the
#     instrument reports becomes an intermediate response plus the instance's progress;
#   * an unknown station becomes the Feature's declared `InvalidStation` error, which is what the
#     real server raises; every other failure is re-raised as the built-in type SiLA2 clients
#     have always seen (`builtin_errors`).
#
# `LightIsOn` also answers, out of the Ardea device's opaque state in the world model.
#
# Everything else refuses (see `unimplemented.py`): `PickLabware` / `PutLabware` are the halves
# of a transfer that only make sense with a carriage the mock cannot position and an arm pose
# it does not track, `MoveHand` / `ActivateHand` drive a gripper that has no counterpart here,
# and `ToggleLight` is left out because the decision was to implement the properties and not
# the actuators -- an operator changes the light through the world model instead.
#
# The Feature XML does not describe a status property for this feature, so unlike the
# instrument controllers in this lab there is no Idle/Running bracket to keep: a transfer's
# progress is reported through its intermediate responses, which is what the real server does.
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from mock_instruments.errors import UnknownStation, builtin_errors
from mock_instruments.runtime import CallbackExecution

from ..generated.labwareservice import (
    ActivateHand_IntermediateResponses,
    ActivateHand_Responses,
    InvalidStation,
    LabwareServiceBase,
    MoveHand_IntermediateResponses,
    MoveHand_Responses,
    PickLabware_IntermediateResponses,
    PickLabware_Responses,
    PutLabware_IntermediateResponses,
    PutLabware_Responses,
    ToggleLight_Responses,
    Transfer_IntermediateResponses,
    Transfer_Responses,
)
from .unimplemented import unimplemented

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)

_FEATURE = "LabwareService"


class LabwareServiceImpl(LabwareServiceBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._instrument = parent_server.instrument

    # ---- the one command this mock performs ----

    def Transfer(
        self,
        SourceStation: str,
        DestinationStation: str,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[Transfer_IntermediateResponses],
    ) -> Transfer_Responses:
        source = str(SourceStation).strip()
        destination = str(DestinationStation).strip()
        logger.info("LabwareService.Transfer called: source=%s destination=%s", source, destination)

        def report(phase: str, progress: float) -> None:
            instance.send_intermediate_response(Transfer_IntermediateResponses(Phase=phase))
            # The ignore is a sila2 typing quirk, not a real constraint: `progress` does have a
            # setter, but it is declared after an unrelated property, which mypy reads as the
            # property being read-only.
            instance.progress = progress  # type: ignore[misc]

        execution = CallbackExecution(begin=instance.begin_execution, report=report)
        with builtin_errors():
            try:
                result = self._instrument.transfer(source, destination, execution)
            except UnknownStation as error:
                # Converted inside `builtin_errors`, which lets the declared SiLA2 error through
                # untouched (it is not an instrument error) and handles every other kind.
                raise InvalidStation(str(error)) from error
        return Transfer_Responses(CarriagePosition=result.carriage_position, AtRetractPose=result.at_retract_pose)

    # ---- the machine light: a read of the world model's device state ----

    def get_LightIsOn(self, *, metadata: MetadataDict) -> bool:
        with builtin_errors():
            return self._instrument.light_is_on(command_name=f"{_FEATURE}.LightIsOn")

    # ---- refused: hardware this world model has no counterpart for ----

    def ToggleLight(self, *, metadata: MetadataDict) -> ToggleLight_Responses:
        unimplemented(_FEATURE, "ToggleLight")

    def PickLabware(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[PickLabware_IntermediateResponses],
    ) -> PickLabware_Responses:
        unimplemented(_FEATURE, "PickLabware")

    def PutLabware(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[PutLabware_IntermediateResponses],
    ) -> PutLabware_Responses:
        unimplemented(_FEATURE, "PutLabware")

    def MoveHand(
        self,
        Position: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[MoveHand_IntermediateResponses],
    ) -> MoveHand_Responses:
        unimplemented(_FEATURE, "MoveHand")

    def ActivateHand(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[ActivateHand_IntermediateResponses],
    ) -> ActivateHand_Responses:
        unimplemented(_FEATURE, "ActivateHand")
