# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of RobotService. Both commands refuse.
#
# The third `bcap-sila2` provider feature (see `variableservice_impl.py`). It reads the arm's
# current joint angles and cartesian position off the robot controller -- the measurement
# Ardea's pose checks are built on.
#
# It refuses for the same reason `RobotPoseService` does: the world model holds no arm
# geometry, so any six numbers this returned would be invented, and a client asking where the
# arm is asks because it is about to decide whether moving is safe.
from __future__ import annotations

import logging

from sila2.server import MetadataDict

from ..generated.robotservice import GetCartesianPosition_Responses, GetJointAngles_Responses, RobotServiceBase
from .unimplemented import unimplemented

logger = logging.getLogger(__name__)

_FEATURE = "RobotService"


class RobotServiceImpl(RobotServiceBase):
    def GetJointAngles(self, *, metadata: MetadataDict) -> GetJointAngles_Responses:
        unimplemented(_FEATURE, "GetJointAngles")

    def GetCartesianPosition(self, *, metadata: MetadataDict) -> GetCartesianPosition_Responses:
        unimplemented(_FEATURE, "GetCartesianPosition")
