# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of Ardea's RobotPoseService. Every command refuses.
#
# These four commands answer "is the arm at this named pose", by reading the robot's joint
# angles over b-CAP and comparing them against the machine's measured reference poses. The
# world model records where labware sits, not how a six-axis arm is folded, so there is
# nothing here to compare against and no honest answer to give: replying `false` would be a
# fabrication, and replying `true` would be a dangerous one -- a client uses these to decide
# whether it is safe to move.
from __future__ import annotations

import logging

from sila2.server import MetadataDict

from ..generated.robotposeservice import (
    IsAtBasePose_Responses,
    IsAtInverseBasePose_Responses,
    IsAtInverseRetractPose_Responses,
    IsAtRetractPose_Responses,
    RobotPoseServiceBase,
)
from .unimplemented import unimplemented

logger = logging.getLogger(__name__)

_FEATURE = "RobotPoseService"


class RobotPoseServiceImpl(RobotPoseServiceBase):
    def IsAtBasePose(self, *, metadata: MetadataDict) -> IsAtBasePose_Responses:
        unimplemented(_FEATURE, "IsAtBasePose")

    def IsAtRetractPose(self, *, metadata: MetadataDict) -> IsAtRetractPose_Responses:
        unimplemented(_FEATURE, "IsAtRetractPose")

    def IsAtInverseBasePose(self, *, metadata: MetadataDict) -> IsAtInverseBasePose_Responses:
        unimplemented(_FEATURE, "IsAtInverseBasePose")

    def IsAtInverseRetractPose(self, *, metadata: MetadataDict) -> IsAtInverseRetractPose_Responses:
        unimplemented(_FEATURE, "IsAtInverseRetractPose")
