# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written SiLA2 adapter for the microplate centrifuge feature. The behaviour itself -- the
# door and its effect on location accessibility, the plate precondition of SpinCycle, bucket
# validation, durations and the Status contract -- is `mock_instruments.centrifuge.Centrifuge`;
# this class maps each SiLA2 command and property onto it:
#
#   * an observable command passes `instance.begin_execution` in as the instrument's
#     `execution.begin`, so execution starts at exactly the point the instrument chooses;
#   * the instrument's Status is published through `update_Status`;
#   * the instrument's protocol-neutral errors are re-raised as the built-in types SiLA2
#     clients have always seen (`builtin_errors`).
#
# Many command parameters are accepted for signature fidelity but not simulated; they are logged
# here and not passed on.
from __future__ import annotations

import logging
from datetime import timedelta
from queue import Queue
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstance

from mock_instruments.errors import builtin_errors
from mock_instruments.runtime import CallbackExecution, Status

from ..generated.microplatecentrifugecontroller import (
    CloseDoor_Responses,
    EnumerateProfiles_Responses,
    Home_Responses,
    LoadPlate_Responses,
    MicroplateCentrifugeControllerBase,
    OpenDoor_Responses,
    Park_Responses,
    Reset_Responses,
    SpinCycle_Responses,
    StopSpinCycle_Responses,
    UnloadPlate_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)


class MicroplateCentrifugeControllerImpl(MicroplateCentrifugeControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._instrument = parent_server.instrument

        # Keep observable command instances alive well beyond their brief mock runtime so a
        # slow client can still poll them to completion.
        self.OpenDoor_default_lifetime_of_execution = timedelta(minutes=30)
        self.CloseDoor_default_lifetime_of_execution = timedelta(minutes=30)
        self.SpinCycle_default_lifetime_of_execution = timedelta(minutes=30)
        self.StopSpinCycle_default_lifetime_of_execution = timedelta(minutes=30)
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)
        self.Home_default_lifetime_of_execution = timedelta(minutes=30)
        self.Park_default_lifetime_of_execution = timedelta(minutes=30)
        self.LoadPlate_default_lifetime_of_execution = timedelta(minutes=30)
        self.UnloadPlate_default_lifetime_of_execution = timedelta(minutes=30)

        # Publish every Status change as the SiLA2 property; subscribing also publishes the
        # value the instrument came up in.
        self._instrument.status.subscribe(self._publish_status)

    def _publish_status(self, status: Status) -> None:
        self.update_Status(int(status))

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Queue[int] | None:
        # Emit the current status immediately to a new subscriber; fall back to Idle (1).
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    # --- Version getters: static mock readouts, no status effect. ---

    def get_ActiveXVersion(self, *, metadata: MetadataDict) -> str:
        return self._instrument.active_x_version

    def get_CentrifugeActiveXVersion(self, *, metadata: MetadataDict) -> str:
        return self._instrument.centrifuge_active_x_version

    def get_CentrifugeHardwareVersion(self, *, metadata: MetadataDict) -> str:
        return self._instrument.centrifuge_hardware_version

    def get_FirmwareVersion(self, *, metadata: MetadataDict) -> str:
        return self._instrument.firmware_version

    def get_HardwareVersion(self, *, metadata: MetadataDict) -> str:
        return self._instrument.hardware_version

    def EnumerateProfiles(self, *, metadata: MetadataDict) -> EnumerateProfiles_Responses:
        logger.info("MicroplateCentrifugeController.EnumerateProfiles called")
        return EnumerateProfiles_Responses(self._instrument.profiles)

    # --- Observable commands. ---

    def OpenDoor(
        self, BucketNumber: int, *, metadata: MetadataDict, instance: ObservableCommandInstance
    ) -> OpenDoor_Responses:
        logger.info("MicroplateCentrifugeController.OpenDoor called: bucket_number=%s", BucketNumber)
        with builtin_errors():
            self._instrument.open_door(BucketNumber, CallbackExecution(begin=instance.begin_execution))
        return OpenDoor_Responses()

    def CloseDoor(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> CloseDoor_Responses:
        logger.info("MicroplateCentrifugeController.CloseDoor called")
        with builtin_errors():
            self._instrument.close_door(CallbackExecution(begin=instance.begin_execution))
        return CloseDoor_Responses()

    def SpinCycle(
        self,
        VelocityPercent: float,
        AccelerationPercent: float,
        DecelerationPercent: float,
        TimerMode: int,
        Time: int,
        BucketNumberToLoad: int,
        BucketNumberToUnload: int,
        GripperOffsetToLoad: float,
        GripperOffsetToUnload: float,
        PlateHeightToLoad: float,
        PlateHeightToUnload: float,
        SpeedToLoad: int,
        SpeedToUnload: int,
        OptionsToLoad: int,
        OptionsToUnload: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> SpinCycle_Responses:
        logger.info(
            "MicroplateCentrifugeController.SpinCycle called: velocity_percent=%s acceleration_percent=%s "
            "deceleration_percent=%s timer_mode=%s time=%s bucket_number_to_load=%s bucket_number_to_unload=%s",
            VelocityPercent,
            AccelerationPercent,
            DecelerationPercent,
            TimerMode,
            Time,
            BucketNumberToLoad,
            BucketNumberToUnload,
        )
        with builtin_errors():
            self._instrument.spin_cycle(Time, CallbackExecution(begin=instance.begin_execution))
        return SpinCycle_Responses()

    def StopSpinCycle(
        self, BucketNumber: int, *, metadata: MetadataDict, instance: ObservableCommandInstance
    ) -> StopSpinCycle_Responses:
        logger.info("MicroplateCentrifugeController.StopSpinCycle called: bucket_number=%s", BucketNumber)
        with builtin_errors():
            self._instrument.stop_spin_cycle(BucketNumber, CallbackExecution(begin=instance.begin_execution))
        return StopSpinCycle_Responses()

    def Reset(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> Reset_Responses:
        logger.info("MicroplateCentrifugeController.Reset called")
        with builtin_errors():
            self._instrument.reset(CallbackExecution(begin=instance.begin_execution))
        return Reset_Responses()

    def Home(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> Home_Responses:
        logger.info("MicroplateCentrifugeController.Home called")
        with builtin_errors():
            self._instrument.home(CallbackExecution(begin=instance.begin_execution))
        return Home_Responses()

    def Park(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> Park_Responses:
        logger.info("MicroplateCentrifugeController.Park called")
        with builtin_errors():
            self._instrument.park(CallbackExecution(begin=instance.begin_execution))
        return Park_Responses()

    def LoadPlate(
        self,
        BucketNumber: int,
        GripperOffset: float,
        PlateHeight: float,
        Speed: int,
        Options: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> LoadPlate_Responses:
        logger.info(
            "MicroplateCentrifugeController.LoadPlate called: bucket_number=%s gripper_offset=%s plate_height=%s "
            "speed=%s options=%s",
            BucketNumber,
            GripperOffset,
            PlateHeight,
            Speed,
            Options,
        )
        with builtin_errors():
            self._instrument.load_plate(BucketNumber, CallbackExecution(begin=instance.begin_execution))
        return LoadPlate_Responses()

    def UnloadPlate(
        self,
        BucketNumber: int,
        GripperOffset: float,
        PlateHeight: float,
        Speed: int,
        Options: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> UnloadPlate_Responses:
        logger.info(
            "MicroplateCentrifugeController.UnloadPlate called: bucket_number=%s gripper_offset=%s plate_height=%s "
            "speed=%s options=%s",
            BucketNumber,
            GripperOffset,
            PlateHeight,
            Speed,
            Options,
        )
        with builtin_errors():
            self._instrument.unload_plate(BucketNumber, CallbackExecution(begin=instance.begin_execution))
        return UnloadPlate_Responses()
