# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of Ardea's RobotOrientationService. Both commands refuse.
#
# The rail is served from both sides, so the machine turns the arm 180 degrees to face a
# station behind it, and parks it at the base pose when it is done. Both motions run
# dedicated PacScripts on the robot controller and are verified by reading the joint angles
# back. Neither the turn nor the park moves any labware, so neither leaves a trace in a world
# model that records where labware sits -- there would be nothing for the mock to do and
# nothing for a client to check afterwards. A transfer that needs the arm turned turns it
# itself, as part of the route.
from __future__ import annotations

import logging

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from ..generated.robotorientationservice import (
    ReturnHome_IntermediateResponses,
    ReturnHome_Responses,
    RobotOrientationServiceBase,
    SetOrientation_IntermediateResponses,
    SetOrientation_Responses,
)
from .unimplemented import unimplemented

logger = logging.getLogger(__name__)

_FEATURE = "RobotOrientationService"


class RobotOrientationServiceImpl(RobotOrientationServiceBase):
    def SetOrientation(
        self,
        Direction: str,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[SetOrientation_IntermediateResponses],
    ) -> SetOrientation_Responses:
        unimplemented(_FEATURE, "SetOrientation")

    def ReturnHome(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[ReturnHome_IntermediateResponses],
    ) -> ReturnHome_Responses:
        unimplemented(_FEATURE, "ReturnHome")
