# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of VariableService. Every command refuses.
#
# This is not an Ardea feature: it belongs to `bcap-sila2`, the DENSO robot-controller provider
# that the real Ardea server vendors and exposes alongside its own features. It reads and
# writes named variables on the controller -- the raw register access underneath everything
# else, used for commissioning and debugging.
#
# The mock serves the feature because the real server does (a client that enumerates features
# must see the same nine), and refuses every command because there is no controller behind it:
# a variable namespace has no counterpart in a world model, and a mock that accepted writes
# into a dictionary would invite a workflow to keep state somewhere the real machine would
# not.
from __future__ import annotations

import logging

from sila2.server import MetadataDict

from ..generated.variableservice import (
    GetVariableNames_Responses,
    ReadVariable_Responses,
    VariableDataType,
    VariableServiceBase,
    WriteVariable_Responses,
)
from .unimplemented import unimplemented

logger = logging.getLogger(__name__)

_FEATURE = "VariableService"


class VariableServiceImpl(VariableServiceBase):
    def ReadVariable(self, VariableName: str, *, metadata: MetadataDict) -> ReadVariable_Responses:
        unimplemented(_FEATURE, "ReadVariable")

    def WriteVariable(
        self, VariableName: str, Value: str, DataType: VariableDataType, *, metadata: MetadataDict
    ) -> WriteVariable_Responses:
        unimplemented(_FEATURE, "WriteVariable")

    def GetVariableNames(self, *, metadata: MetadataDict) -> GetVariableNames_Responses:
        unimplemented(_FEATURE, "GetVariableNames")
