# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of TaskService. Every command refuses.
#
# Another feature of the `bcap-sila2` provider rather than of Ardea itself (see
# `variableservice_impl.py` for why the mock serves it at all). `RunTask` runs a named PAC
# program on the robot controller and waits for it to finish -- which is the layer Ardea's own
# pick, put and turn commands are built out of.
#
# It refuses because the task names are the machine's, not this repository's: they exist on one
# particular controller, they move a real arm, and there is nothing in the world model for
# "the arm executed a trajectory" to mean. A mock that accepted any task name and returned
# success would be the easiest way for a workflow to become untestable -- it would pass here
# and do something physical there.
from __future__ import annotations

import logging

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.taskservice import GetTaskNames_Responses, RunTask_Responses, TaskServiceBase
from .unimplemented import unimplemented

logger = logging.getLogger(__name__)

_FEATURE = "TaskService"


class TaskServiceImpl(TaskServiceBase):
    def GetTaskNames(self, *, metadata: MetadataDict) -> GetTaskNames_Responses:
        unimplemented(_FEATURE, "GetTaskNames")

    def RunTask(
        self, TaskName: str, *, metadata: MetadataDict, instance: ObservableCommandInstance
    ) -> RunTask_Responses:
        unimplemented(_FEATURE, "RunTask")
