# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written SiLA2 adapter for the PlateLoc (plate sealer) feature. The behaviour itself --
# setpoints, cycle count, the plate precondition, durations and the Status contract -- is
# `mock_instruments.plateloc.PlateLoc`; this class maps each SiLA2 command and property onto it:
#
#   * an observable command passes `instance.begin_execution` in as the instrument's
#     `execution.begin`, so execution starts at exactly the point the instrument chooses;
#   * the instrument's Status is published through `update_Status`;
#   * the instrument's protocol-neutral errors are re-raised as the built-in types SiLA2
#     clients have always seen (`builtin_errors`).
from __future__ import annotations

import logging
from datetime import timedelta
from queue import Queue
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstance

from mock_instruments.errors import builtin_errors
from mock_instruments.runtime import CallbackExecution, Status

from ..generated.plateloccontroller import (
    EnumerateProfiles_Responses,
    PlateLocControllerBase,
    Reset_Responses,
    SetSealingTemperature_Responses,
    SetSealingTime_Responses,
    StartCycle_Responses,
    StopCycle_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)


class PlateLocControllerImpl(PlateLocControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._instrument = parent_server.instrument

        # Keep observable command instances pollable well beyond their brief mock runtime.
        self.StartCycle_default_lifetime_of_execution = timedelta(minutes=30)
        self.StopCycle_default_lifetime_of_execution = timedelta(minutes=30)
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)

        # Publish every Status change as the SiLA2 property; subscribing also publishes the
        # value the instrument came up in.
        self._instrument.status.subscribe(self._publish_status)

    def _publish_status(self, status: Status) -> None:
        self.update_Status(int(status))

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Queue[int] | None:
        # Emit the current status immediately to a new subscriber; fall back to Idle (1).
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    # --- Getters: state readouts, no status effect. ---

    def get_SealingTemperature(self, *, metadata: MetadataDict) -> int:
        return self._instrument.sealing_temperature

    def get_SealingTime(self, *, metadata: MetadataDict) -> float:
        return self._instrument.sealing_time

    def get_ActualTemperature(self, *, metadata: MetadataDict) -> int:
        return self._instrument.actual_temperature

    def get_CycleCount(self, *, metadata: MetadataDict) -> int:
        return self._instrument.cycle_count

    def get_FirmwareVersion(self, *, metadata: MetadataDict) -> str:
        return self._instrument.firmware_version

    def get_Version(self, *, metadata: MetadataDict) -> str:
        return self._instrument.version

    # --- Unobservable commands. ---

    def SetSealingTime(self, SealingTime: float, *, metadata: MetadataDict) -> SetSealingTime_Responses:
        logger.info("PlateLocController.SetSealingTime called: sealing_time=%s", SealingTime)
        with builtin_errors():
            self._instrument.set_sealing_time(SealingTime)
        return SetSealingTime_Responses()

    def SetSealingTemperature(
        self, SealingTemperature: int, *, metadata: MetadataDict
    ) -> SetSealingTemperature_Responses:
        logger.info("PlateLocController.SetSealingTemperature called: sealing_temperature=%s", SealingTemperature)
        with builtin_errors():
            self._instrument.set_sealing_temperature(SealingTemperature)
        return SetSealingTemperature_Responses()

    def EnumerateProfiles(self, *, metadata: MetadataDict) -> EnumerateProfiles_Responses:
        logger.info("PlateLocController.EnumerateProfiles called")
        return EnumerateProfiles_Responses(self._instrument.profiles)

    # --- Observable commands. ---

    def StartCycle(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> StartCycle_Responses:
        logger.info("PlateLocController.StartCycle called")
        with builtin_errors():
            self._instrument.start_cycle(CallbackExecution(begin=instance.begin_execution))
        return StartCycle_Responses()

    def StopCycle(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> StopCycle_Responses:
        logger.info("PlateLocController.StopCycle called")
        with builtin_errors():
            self._instrument.stop_cycle(CallbackExecution(begin=instance.begin_execution))
        return StopCycle_Responses()

    def Reset(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> Reset_Responses:
        logger.info("PlateLocController.Reset called")
        with builtin_errors():
            self._instrument.reset(CallbackExecution(begin=instance.begin_execution))
        return Reset_Responses()
