# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written beyond the codegen scaffold. This is the mock of Ardea, a real machine whose
# SiLA2 server (`ardea-sila2`) drives a DENSO robot arm on a travel carriage over ORiN b-CAP
# and a KEYENCE PLC over the KV COM+ Library. It replaced the trolley arm as this lab's
# transporter, and it is the one server here whose Feature definitions come from a real
# instrument -- all nine of them, unchanged, so a workflow written against this mock can be
# pointed at the machine (see `protocols/sila2/specs/ardea_server/README.md`).
#
# WHAT IS MOCKED AND WHAT IS NOT. Only `LabwareService.Transfer` performs work, because it is
# the one command a workflow needs from a transporter: carry a labware from one station to
# another. Everything else the real server offers -- the individual pick and put, the carriage
# and hand actuators, the pose checks, and the two providers' low-level variable/task/PLC
# access -- raises NotImplementedError, which SiLA reports as an undefined execution error.
# That is a deliberate floor rather than an unfinished state: those commands drive hardware
# this world model has no counterpart for, and a mock that pretended to run them would let a
# workflow come to depend on behaviour nothing here checks. The Feature definitions still
# declare them, which is what keeps the swap with the real server possible.
#
# Three read-only properties DO answer, because the world model already holds what they
# report: the station names, the carriage position, and the machine light.
#
# What the transfer does, how those three values are derived, and the station map are the
# instrument's, not this server's: they live in `mock_instruments.ardea`, which the LADS OPC UA
# server of the same transporter uses too. This server only speaks SiLA2 for it -- including the
# twenty-two refusals, since what a refusal looks like is SiLA2 vocabulary.

import os
from uuid import UUID, uuid4

from sila2.server import SilaServer

from mock_instruments.ardea import Ardea

from .feature_implementations.carriageservice_impl import CarriageServiceImpl
from .feature_implementations.connectionservice_impl import ConnectionServiceImpl
from .feature_implementations.deviceservice_impl import DeviceServiceImpl
from .feature_implementations.labwareservice_impl import LabwareServiceImpl
from .feature_implementations.robotorientationservice_impl import RobotOrientationServiceImpl
from .feature_implementations.robotposeservice_impl import RobotPoseServiceImpl
from .feature_implementations.robotservice_impl import RobotServiceImpl
from .feature_implementations.taskservice_impl import TaskServiceImpl
from .feature_implementations.variableservice_impl import VariableServiceImpl
from .generated.carriageservice import CarriageServiceFeature
from .generated.connectionservice import ConnectionServiceFeature
from .generated.deviceservice import DeviceServiceFeature
from .generated.labwareservice import LabwareServiceFeature
from .generated.robotorientationservice import RobotOrientationServiceFeature
from .generated.robotposeservice import RobotPoseServiceFeature
from .generated.robotservice import RobotServiceFeature
from .generated.taskservice import TaskServiceFeature
from .generated.variableservice import VariableServiceFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: UUID | None = None,
        name: str | None = None,
        description: str | None = None,
    ):
        # Server identity comes from the environment so compose can configure each instance.
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")
        # The transporter reads its world-model wiring, its station map (`ARDEA_STATIONS`) and
        # its command durations from the environment as well. Anything set but unusable -- a
        # typo in the station map included -- raises here, during construction, so a
        # misconfigured container fails at startup instead of at its first transfer.
        self.instrument = Ardea.from_environment()

        if name is None:
            name = env_name if env_name else "ArdeaServer"
        if description is None:
            description = (
                "Mock of the Ardea SiLA2 server: a robot arm on a travel carriage that moves "
                "labware between the lab's stations. It serves the real machine's nine Feature "
                "definitions unchanged, but implements only LabwareService.Transfer and the "
                "read-only properties the world model can answer."
            )
        # The server type is the real machine's, because that is the name a client looking for
        # Ardea knows it by; the description above is where being a mock is said out loud.
        server_type = env_type if env_type else "ArdeaSila2Server"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        # The nine features, registered in the same order the real server registers them: the
        # b-CAP provider's three, the KV COM+ provider's two, then Ardea's own four.
        self.variableservice = VariableServiceImpl(self)
        self.set_feature_implementation(VariableServiceFeature, self.variableservice)

        self.taskservice = TaskServiceImpl(self)
        self.set_feature_implementation(TaskServiceFeature, self.taskservice)

        self.robotservice = RobotServiceImpl(self)
        self.set_feature_implementation(RobotServiceFeature, self.robotservice)

        self.deviceservice = DeviceServiceImpl(self)
        self.set_feature_implementation(DeviceServiceFeature, self.deviceservice)

        self.connectionservice = ConnectionServiceImpl(self)
        self.set_feature_implementation(ConnectionServiceFeature, self.connectionservice)

        self.robotposeservice = RobotPoseServiceImpl(self)
        self.set_feature_implementation(RobotPoseServiceFeature, self.robotposeservice)

        self.carriageservice = CarriageServiceImpl(self)
        self.set_feature_implementation(CarriageServiceFeature, self.carriageservice)

        self.labwareservice = LabwareServiceImpl(self)
        self.set_feature_implementation(LabwareServiceFeature, self.labwareservice)

        self.robotorientationservice = RobotOrientationServiceImpl(self)
        self.set_feature_implementation(RobotOrientationServiceFeature, self.robotorientationservice)
