# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written SiLA2 adapter for the thermal cycler feature. The behaviour itself -- the
# Load -> Validate -> StartRun ordering, the lid and its effect on location accessibility, the
# plate precondition of StartRun, durations, the elapsed/remaining readouts and the Status
# contract (including StartRun leaving Status at Running, and the lid commands staying at Idle)
# -- is `mock_instruments.thermal_cycler.ThermalCycler`; this class maps each SiLA2 command and
# property onto it:
#
#   * an observable command passes `instance.begin_execution` in as the instrument's
#     `execution.begin`, so execution starts at exactly the point the instrument chooses;
#   * the instrument's Status, ElapsedTime and RemainingTime are published through the
#     generated `update_*` methods;
#   * the instrument's protocol-neutral errors are re-raised as the built-in types SiLA2
#     clients have always seen (`builtin_errors`).
from __future__ import annotations

import logging
from datetime import timedelta
from queue import Queue
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstance

from mock_instruments.errors import builtin_errors
from mock_instruments.runtime import CallbackExecution, Status

from ..generated.automatedthermalcyclercontroller import (
    AutomatedThermalCyclerControllerBase,
    CloseLid_Responses,
    GetInstrumentState_Responses,
    Load_Responses,
    OpenLid_Responses,
    Reset_Responses,
    StartRun_Responses,
    StopRun_Responses,
    Validate_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)


class AutomatedThermalCyclerControllerImpl(AutomatedThermalCyclerControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._instrument = parent_server.instrument

        # Keep observable command instances alive for 30 min (well beyond their brief mock
        # runtime) so a slow client can still poll them to completion.
        self.Load_default_lifetime_of_execution = timedelta(minutes=30)
        self.Validate_default_lifetime_of_execution = timedelta(minutes=30)
        self.OpenLid_default_lifetime_of_execution = timedelta(minutes=30)
        self.CloseLid_default_lifetime_of_execution = timedelta(minutes=30)
        self.StartRun_default_lifetime_of_execution = timedelta(minutes=30)
        self.StopRun_default_lifetime_of_execution = timedelta(minutes=30)
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)

        # Publish the instrument's observable values as the SiLA2 properties; subscribing also
        # publishes the values the instrument came up in.
        self._instrument.elapsed_time.subscribe(self.update_ElapsedTime)
        self._instrument.remaining_time.subscribe(self.update_RemainingTime)
        self._instrument.status.subscribe(self._publish_status)

    def _publish_status(self, status: Status) -> None:
        self.update_Status(int(status))

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Queue[int] | None:
        # On a new subscription, immediately emit the current status so the subscriber does
        # not have to wait for the next change. Fall back to Idle (1) if none set yet.
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    def GetInstrumentState(self, *, metadata: MetadataDict) -> GetInstrumentState_Responses:
        # Returns the `InstrumentState` enum (NOT the Status enum).
        logger.info("AutomatedThermalCyclerController.GetInstrumentState called")
        return GetInstrumentState_Responses(int(self._instrument.get_instrument_state()))

    def Load(
        self, ProtocolFileData: bytes, *, metadata: MetadataDict, instance: ObservableCommandInstance
    ) -> Load_Responses:
        logger.info("AutomatedThermalCyclerController.Load called: protocol_size=%s", len(ProtocolFileData))
        with builtin_errors():
            self._instrument.load(ProtocolFileData, CallbackExecution(begin=instance.begin_execution))
        return Load_Responses()

    def Validate(
        self, MaxSampleVolume: float, *, metadata: MetadataDict, instance: ObservableCommandInstance
    ) -> Validate_Responses:
        logger.info("AutomatedThermalCyclerController.Validate called: max_sample_volume=%s", MaxSampleVolume)
        with builtin_errors():
            self._instrument.validate(MaxSampleVolume, CallbackExecution(begin=instance.begin_execution))
        return Validate_Responses()

    def OpenLid(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> OpenLid_Responses:
        logger.info("AutomatedThermalCyclerController.OpenLid called")
        with builtin_errors():
            self._instrument.open_lid(CallbackExecution(begin=instance.begin_execution))
        return OpenLid_Responses()

    def CloseLid(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> CloseLid_Responses:
        logger.info("AutomatedThermalCyclerController.CloseLid called")
        with builtin_errors():
            self._instrument.close_lid(CallbackExecution(begin=instance.begin_execution))
        return CloseLid_Responses()

    def StartRun(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> StartRun_Responses:
        logger.info("AutomatedThermalCyclerController.StartRun called")
        with builtin_errors():
            self._instrument.start_run(CallbackExecution(begin=instance.begin_execution))
        return StartRun_Responses()

    def StopRun(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> StopRun_Responses:
        logger.info("AutomatedThermalCyclerController.StopRun called")
        with builtin_errors():
            self._instrument.stop_run(CallbackExecution(begin=instance.begin_execution))
        return StopRun_Responses()

    def Reset(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> Reset_Responses:
        logger.info("AutomatedThermalCyclerController.Reset called")
        with builtin_errors():
            self._instrument.reset(CallbackExecution(begin=instance.begin_execution))
        return Reset_Responses()
