# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written SiLA2 adapter for the automated plate seal remover (peeler) feature. The
# behaviour itself -- the two tape reserves, the LOW_TAPE warning, input ranges, the plate
# precondition, durations and the Status contract -- is
# `mock_instruments.seal_remover.SealRemover`; this class maps each SiLA2 command and property
# onto it:
#
#   * an observable command passes `instance.begin_execution` in as the instrument's
#     `execution.begin`, so execution starts at exactly the point the instrument chooses;
#   * the instrument's Status is published through `update_Status`;
#   * the instrument's protocol-neutral errors are re-raised as the built-in types SiLA2
#     clients have always seen (`builtin_errors`).
from __future__ import annotations

import logging
from datetime import timedelta
from queue import Queue
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstance

from mock_instruments.errors import builtin_errors
from mock_instruments.runtime import CallbackExecution, Status

from ..generated.automatedplatesealremovercontroller import (
    AutomatedPlateSealRemoverControllerBase,
    GetTapeLeft_Responses,
    Peel_Responses,
    Reset_Responses,
    ResetInstrument_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)


class AutomatedPlateSealRemoverControllerImpl(AutomatedPlateSealRemoverControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._instrument = parent_server.instrument

        # Keep observable command instances pollable well beyond their brief mock runtime.
        self.Peel_default_lifetime_of_execution = timedelta(minutes=30)
        self.GetTapeLeft_default_lifetime_of_execution = timedelta(minutes=30)
        self.ResetInstrument_default_lifetime_of_execution = timedelta(minutes=30)
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)

        # Publish every Status change as the SiLA2 property; subscribing also publishes the
        # value the instrument came up in.
        self._instrument.status.subscribe(self._publish_status)

    def _publish_status(self, status: Status) -> None:
        self.update_Status(int(status))

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Queue[int] | None:
        # Emit the current status immediately to a new subscriber; fall back to Idle (1).
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    def Peel(
        self,
        BeginPeelLocation: int,
        AdhesionTime: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Peel_Responses:
        logger.info(
            "AutomatedPlateSealRemoverController.Peel called: begin_peel_location=%s adhesion_time=%s",
            BeginPeelLocation,
            AdhesionTime,
        )
        with builtin_errors():
            warning = self._instrument.peel(
                BeginPeelLocation, AdhesionTime, CallbackExecution(begin=instance.begin_execution)
            )
        return Peel_Responses(warning)

    def GetTapeLeft(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> GetTapeLeft_Responses:
        logger.info("AutomatedPlateSealRemoverController.GetTapeLeft called")
        with builtin_errors():
            tape = self._instrument.get_tape_left(CallbackExecution(begin=instance.begin_execution))
        return GetTapeLeft_Responses(tape.supply_spool_remaining, tape.takeup_spool_remaining, tape.warning)

    def ResetInstrument(
        self, *, metadata: MetadataDict, instance: ObservableCommandInstance
    ) -> ResetInstrument_Responses:
        logger.info("AutomatedPlateSealRemoverController.ResetInstrument called")
        with builtin_errors():
            self._instrument.reset_instrument(CallbackExecution(begin=instance.begin_execution))
        return ResetInstrument_Responses("")

    def Reset(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> Reset_Responses:
        logger.info("AutomatedPlateSealRemoverController.Reset called")
        with builtin_errors():
            self._instrument.reset(CallbackExecution(begin=instance.begin_execution))
        return Reset_Responses("")
