# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written beyond the codegen scaffold: the constructor reads the server's identity from the
# environment and builds the instrument this server exposes. Everything the instrument *does* --
# its door, its rules, how long commands take, its Status, and its bridge to the shared world
# model (a spin needs a plate; the door toggles the location's accessibility) -- lives in
# `mock_instruments.centrifuge`, which the LADS OPC UA server of the same instrument uses too.
# This server only speaks SiLA2 for it.

import os
from uuid import UUID, uuid4

from sila2.server import SilaServer

from mock_instruments.centrifuge import Centrifuge

from .feature_implementations.microplatecentrifugecontroller_impl import MicroplateCentrifugeControllerImpl
from .generated.microplatecentrifugecontroller import MicroplateCentrifugeControllerFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: UUID | None = None,
        name: str | None = None,
        description: str | None = None,
    ):
        # Server identity comes from the environment so compose can configure each instance.
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")
        # The instrument reads its world-model wiring and command durations from the environment
        # as well. A variable that is set but unusable raises here, during construction, so a
        # misconfigured container fails at startup instead of at its first command.
        self.instrument = Centrifuge.from_environment()

        if name is None:
            name = env_name if env_name else "MicroplateCentrifugeServer"
        if description is None:
            description = "Mock SiLA2 server for Microplate Centrifuge"
        server_type = env_type if env_type else "MicroplateCentrifugeServer"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.microplatecentrifugecontroller = MicroplateCentrifugeControllerImpl(self)
        self.set_feature_implementation(MicroplateCentrifugeControllerFeature, self.microplatecentrifugecontroller)
